export const lyrics = [
    { time: 0, text: "🎶🎶" },
    { time: 10, text: "Hark! How the bells, sweet silver bells" },
    { time: 12, text: "All seem to say, 'Throw cares away'" },
    { time: 15, text: "Christmas is here, bringing good cheer" },
    { time: 17, text: "To young and old, meek and the bold" },
    { time: 20, text: "Ding, dong, ding, dong, that is their song" },
    { time: 22, text: "With joyful ring, all caroling" },
    { time: 25, text: "One seems to hear, words of good cheer" },
    { time: 27, text: "From everywhere, filling the air" },
    { time: 30, text: "Oh, how they pound, raising the sound" },
    { time: 32, text: "O'er hill and dale, telling their tale" },
    { time: 35, text: "Gaily they ring, while people sing" },
    { time: 37, text: "Songs of good cheer, Christmas is here" },
    { time: 39, text: "Merry, merry, merry, merry Christmas" },
    { time: 41, text: "Merry, merry, merry, merry Christmas" },
    { time: 43, text: "On-on they send, on without end" },
    { time: 46, text: "Their joyful tone to every home" },
    { time: 49, text: "Hark! How the bells, sweet silver bells" },
    { time: 51, text: "All seem to say, 'Throw cares away'" },
    { time: 54, text: "Christmas is here, bringing good cheer" },
    { time: 56, text: "To young and old, meek and the bold" },
    { time: 59, text: "Ding, dong, ding, dong, that is their song" },
    { time: 61, text: "With joyful ring, all caroling" },
    { time: 64, text: "One seems to hear, words of good cheer" },
    { time: 66, text: "From everywhere, filling the air" },
    { time: 69, text: "Oh, how they pound, raising the sound" },
    { time: 71, text: "O'er hill and dale, telling their tale" },
    { time: 73, text: "Gaily they ring, while people sing" },
    { time: 76, text: "Songs of good cheer, Christmas is here" },
    { time: 78, text: "Merry, merry, merry, merry Christmas" },
    { time: 80, text: "Merry, merry, merry, merry Christmas" },
    { time: 83, text: "On-on they send, on without end" },
    { time: 85, text: "Their joyful tone to every home" },
    { time: 88, text: "Hark! How the bells, sweet silver bells" },
    { time: 90, text: "All seem to say, 'Throw cares away'" },
    { time: 92, text: "Christmas is here, bringing good cheer" },
    { time: 95, text: "To young and old, meek and the bold" },
    { time: 97, text: "Ding, dong, ding, dong, that is their song" },
    { time: 99, text: "With joyful ring, all caroling" },
    { time: 102, text: "One seems to hear, words of good cheer" },
    { time: 104, text: "From everywhere, filling the air" },
    { time: 107, text: "Oh, how they pound, raising the sound" },
    { time: 110, text: "O'er hill and dale, telling their tale" },
    { time: 112, text: "Gaily they ring, while people sing" },
    { time: 114, text: "Songs of good cheer, Christmas is here" },
    { time: 116, text: "Merry, merry, merry, merry Christmas" },
    { time: 118, text: "Merry, merry, merry, merry Christmas" },
    { time: 121, text: "On-on they send, on without end" },
    { time: 124, text: "Their joyful tone to every home" },
    { time: 126, text: "On-on they send, on without end" },
    { time: 128, text: "Their joyful tone to every home" },
    { time: 131, text: ""}
];